config/routes.rb
RedditClone::Application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts do
    resources :comments
  end

end

#                 Prefix Verb   URI Pattern                                 Controller#Action
#         new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                    devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
#            user_password POST   /users/password(.:format)                   devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)               devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
#                          PATCH  /users/password(.:format)                   devise/passwords#update
#                          PUT    /users/password(.:format)                   devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                     devise/registrations#cancel
#        user_registration POST   /users(.:format)                            devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                    devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                       devise/registrations#edit
#                          PATCH  /users(.:format)                            devise/registrations#update
#                          PUT    /users(.:format)                            devise/registrations#update
#                          DELETE /users(.:format)                            devise/registrations#destroy
#                     root GET    /                                           posts#index
#            post_comments GET    /posts/:post_id/comments(.:format)          comments#index
#                          POST   /posts/:post_id/comments(.:format)          comments#create
#         new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
#        edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
#             post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
#                          PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
#                          PUT    /posts/:post_id/comments/:id(.:format)      comments#update
#                          DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
#                    posts GET    /posts(.:format)                            posts#index
#                          POST   /posts(.:format)                            posts#create
#                 new_post GET    /posts/new(.:format)                        posts#new
#                edit_post GET    /posts/:id/edit(.:format)                   posts#edit
#                     post GET    /posts/:id(.:format)                        posts#show
#                          PATCH  /posts/:id(.:format)                        posts#update
#                          PUT    /posts/:id(.:format)                        posts#update
#                          DELETE /posts/:id(.:format)                        posts#destroy

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :load_post

	def index
		@comments = @post.comments.all
		@user = current_user
	end

	def new
	 @comment = @post.comments.new
	end

	def create
		@comment = @post.comments.create(comment_params)
		if @comment.save
			redirect_to post_comments_path
		end
	end

	def show
		@comment = @post.comments.find(params[:id])
		@user = current_user
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_comments_path(@post)
	end

	private
		def comment_params
			params[:comment].permit(:body)
		end

		def load_post
			@post = Post.find(params[:post_id])
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
		@user = current_user
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		redirect_to posts_path
  end
	
	private
		def post_params
			params[:post].permit(:title, :body, :comments_attributes=>[:body])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/index.html.erb
<h1>All Comments on "<%=@post.title%>"</h1>

<% @comments.each do |comment| %>
	<%= link_to comment.body, post_comment_path(params[:post_id], comment.id) %> <%= link_to "delete", [@post, comment], method: :delete, data: {confirm: "Are you sure?"} %> <br>

	<p class="commentby">submitted <%= time_ago_in_words(comment.created_at) %> ago by: <strong><%= @user.email %></strong></p>
	
<% end %>
<br>
<div class="buttons">
	<%= link_to "Add a Comment", new_post_comment_path %><br>
	<br>
	<%= link_to "Back to all Posts", posts_path %>
</div>

app/views/comments/new.html.erb
<h1>Add your comment to "<%=@post.title%>"</h1>

<%= form_for([@post, @comment]) do |f| %>
	<%= f.text_field :body, placeholder: "Write Your Comment" %>
	<%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<h2> Comment #<%=@comment.id%> for "<%= @post.title %>"</h2>
<h4><%= @comment.body %> </h4>
<p class="commentby">submitted <%= time_ago_in_words(@comment.created_at) %> ago by: <strong><%= @user.email %></strong> to <strong>/hot </strong></p>

<%= link_to "delete", [@post, @comment], method: :delete, data: {confirm: "Are you sure?"} %> <br>
<%= link_to "Back to all Posts", posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div id="header">
      <p class="topheader">
        MY SUBREDDITS FRONT-ALL-RANDOM | FUNNY-PICS-ASKREDDIT-IAMA-NEWS-TODAYILEARNED-WORLDNEWS-GIFS-VIDEOS-AWW-EXPLAINLIKEIMFIVE-MUSIC-MOVIES-SPORTS- MORE »
      </p>
      <img src="http://newsbtc.com/wp-content/uploads/2013/12/Reddit-logo-small.jpg" id="logo"/>
      <p>
      </p>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>

      <ul id="tabmenu">
        <li><%=link_to "hot", root_path %></li>
        <li><%=link_to "new", root_path %></li>
        <li><%=link_to "rising", root_path %></li>
      </ul>
    
      </div>
    <div class="flash_errors"
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>All Posts </h1>

<div id="posts">
	<% @posts.each do |post| %>
	<%= link_to post.title, post_comments_path(post.id) %><br>
	<% end %>
	<br>
</div>
<%= link_to "Create New Post", new_post_path %>

app/views/posts/new.html.erb
<h1> Create New Post </h1>

<%= form_for @post do |f| %>
	<%= f.text_field :title, placeholder: "Title" %>
	<%= f.text_field :body, placeholder: "Write something" %>
	<%= f.submit %>
<% end %>